name: Python CI

on:
  - push

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
        # Clone the repository
      - uses: actions/checkout@v3
        # Set up Python
      - uses: actions/setup-python@v4
        with:
            python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install poetry
          poetry install --no-root

      - name: Run linter
        run: make lint

      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v3.2.0
        if: github.ref_name == 'main'
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: make test-coverage
          debug: true